trigger:
  branches:
    include:
      - main

variables:
  imageName: 'reactportfolioimage'         
  imageTag: 'latest'                       
#okkkkk
stages:
- stage: BuildAndPush
  displayName: 'Build and Push to ACR'
  jobs:
  - job: Build
    displayName: 'Build and Push'
    pool:
       name: mypool

    steps:
    - checkout: self

    - task: Docker@2
      displayName: 'Build and Push Docker Image'
      inputs:
        containerRegistry: 'my-acr-connection'      
        repository: $(imageName)
        command: buildAndPush
        Dockerfile: '.devcontainer/Dockerfile'
        buildContext: '.' 
       

        tags: |
          $(imageTag)
          $(Build.BuildId)
